### ISSUE TITLE
Update to 1.8

### ISSUE THREAD

**Issue by Telbaru** [LRFLEW/CreativeKill#1]
You sould update your plugin to 1.8.
There are two kinds of errors. Everytime you kill an Enderdragon-crystal you get an error in the console. And everytime you hit an Item in an Itemframe you get an Error.

Itemframe-error:
[09:22:33] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CreativeKill v0.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:538) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:451) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:589) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityItemFrame.damageEntity(EntityItemFrame.java:31) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityHanging.l(EntityHanging.java:181) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:959) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1051) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1312) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-952179b-43207df]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_75]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_75]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-43207df]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R1.entity.CraftItemFrame cannot be cast to org.bukkit.entity.LivingEntity
    at com.LRFLEW.bukkit.ck.CreativeKill.entityDamageEntity(CreativeKill.java:26) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-952179b-43207df]
    ... 22 more

Endercrystal-error:
[09:26:01] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CreativeKill v0.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:538) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:451) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:589) [spigot.jar:git-Spigot-952179b-43207df]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:575) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityEnderCrystal.damageEntity(EntityEnderCrystal.java:63) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:1002) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1051) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1312) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-952179b-43207df]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_75]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_75]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-43207df]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-43207df]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R1.entity.CraftEnderCrystal cannot be cast to org.bukkit.entity.LivingEntity
    at com.LRFLEW.bukkit.ck.CreativeKill.entityDamageEntity(CreativeKill.java:26) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-952179b-43207df]
    ... 22 more

I Use Spigot 1.8 Version: git-Spigot-952179b-43207df (MC: 1.8)

**Comment by LRFLEW** [comment]
I'm not really active in bukkit (or bucket-compatible alternatives) development right now, but I can take a look. Based on your description alone, it sounds like Spigot may call entityDamageEntity for entities that aren't Living Entities. I can insert an additional check, but I don't have the time to test it myself right now. If you'd be willing to help test it, I'll work on it.

**Comment by Telbaru** [comment]
sure i can test it :)

**Comment by Telbaru** [comment]
I tested your fixes and all the problems are away. I tested the other functions and all is perfect :) Thanks!

**Comment by Telbaru** [comment]
Is it possible you set this version online on bukkit?
